Convert chapter 10 (affine transformations)
gbadev-org/tonc pull request #15
Opened 2023-09-06 10:03 UTC by gwilymk

Converts the affine chapter to markdown. This is incomplete pending a decision on #7. Once that has closed, I'll resume and format the equations (I haven't bothered at all here to format them which is why they look so ugly).

2023-09-06 10:23 UTC, avivace commented
Amazing, thanks @gwilymk . I closed the issue on the equations, you can go ahead with MathML ;)

2023-09-06 11:48 UTC, gwilymk commented
mathml was a bit of a pain :upside_down_face:

2023-09-09 01:01 UTC, exelotl commented
Thanks, this is looking really good so far!

Some notes from comparing side-by-side (md on the left, original (with dark theme) on the right):

![](https://github.com/gbadev-org/tonc/assets/569607/2e9dd5bd-a94a-40e4-9747-156bee98a11b)

* Subfigures can be done by assigning an ID to the containing tag for the whole figure rather than subfigures, and manually appending the letter e.g. `{@fig:foo}a` might render as _fig 1.2a_ .
* The two subfigures which shouldn't be side-by-side aren't, and the giant **A→**  isn't rendered right. Might be best to lift more of the original HTML to fix this?
* Vertical spacing around the equations may be needed (I guess you can just use `<br>` unless you feel like adding a CSS rule for equation blocks?)
* Letters in the formulae that used to be bold aren't anymore. I'm no expert mathematician but I guess this sort of thing is important to preserve?
* `{@fig:rotscale_good}` should be `{@fig:rotatescale_good}`.
* There's a couple of instances where the figure/table name ought to be capitalised but isn't (like near the bottom of the screenshot)

2023-09-26 16:00 UTC, gwilymk commented
Sorry, was on holiday for the past two weeks. Plan is to finish this off tomorrow morning :)

2023-09-27 10:47 UTC, avivace commented
@gwilymk amazing, thanks! Will take a look now

2023-09-27 12:06 UTC, avivace approved these changes
Looks great to me! The only thing I'm noticing is the different numbering on the figures: the first side by side gets 10.2 instead of 10.1. Is this intentional?

2023-09-27 12:31 UTC, gwilymk commented
> the first side by side gets 10.2 instead of 10.1. Is this intentional?

It wasn't, but I couldn't work out why it was starting at 10.2 :/. It is the first figure since the one before is an equation. Tried a bunch of different things but none of them worked so hoped someone who knows how to use the referencing thing a bit better would have more luck :)

2023-09-27 12:38 UTC, LunarLambda commented on content/pages/affine.md
> +![](img/affine/metr_rs_good.png){#fig:rotatescale}
You're using the `#fig:rotatescale` id twice, resulting in the figure numbering being wrong. See [exelotl's comments](https://github.com/gbadev-org/tonc/pull/15#issuecomment-1712368738) for how to deal with subfigures.

2023-09-27 14:06 UTC, gwilymk commented on content/pages/affine.md
> +![](img/affine/metr_rs_good.png){#fig:rotatescale}
Only mentioning the figure once fixed it here. Weird behaviour...

2023-09-27 18:02 UTC, LunarLambda commented on content/pages/affine.md
> +![ ... mapped](img/affine/metr_texmapA.png){#fig:metroid_texture}b
There is another duplicated figure id here.

2023-09-28 06:11 UTC, LunarLambda requested changes

2023-09-28 06:11 UTC, LunarLambda commented on content/pages/affine.md
> +Unfortunately, there is a lot of incorrect or misleading information on the transformation matrix around; the matrix of eq 10.1 is just one aspect of it. This actually starts with the moniker “Rot/Sc
This needs to have {@eq:incorrect_transform_matrix}

2023-09-28 06:11 UTC, LunarLambda commented on content/pages/affine.md
> +<math id="eq:correct_transform_matrix" class="block">
This should not have an `eq` id as it's never referred to in TONC's text. This is what's causing `{@eq:inverse_transform}` to show as 10.4 not 10.3

2023-09-28 06:11 UTC, LunarLambda commented on content/pages/affine.md
> +My code for a object version of the scale-then-rotate function (à la {@eq:transformation_matrix}) is given below. Note that it is from the computer's point of view, so that `sx` and `sy` scale down.
This reference is broken. There's no equation with id `transformation_matrix`. You probably wanted `correct_matrix`.

2023-10-27 06:17 UTC, LunarLambda commented
Filenames (i.e. things that were wrapped in `<tt>` tags in the original HTML) should be italicized rather than be wrapped in backticks.

Also, the math spacing is terrible on my system, but I'm not sure if this a font issue:

![image](https://github.com/gbadev-org/tonc/assets/38919842/bf4869a8-96b1-4d91-86b5-4780f3a68bcb)

The figure/equation/table numbering looks all good now.

2023-10-27 18:55 UTC, avivace requested changes

2023-10-27 18:55 UTC, avivace commented on content/pages/affine.md
> +So now you can figure out **P**'s elements in two ways. You can stick to the human POV and invert the matrix at the end. That's why I gave you the inverses of the affine transformations as well. You
Filenames here should go in italic

2023-10-27 19:02 UTC, merged