Port "Chapter 19: Text Systems" to markdown
gbadev-org/tonc pull request #60
Opened 2023-11-06 13:23 UTC by mtthgn

This commit migrates `text.htm` to `text.md`, and converts a few things to play nicely with the mdbook styling.

Most notably, the figure showing bitpacking of fonts required a fair bit of custom CSS. This was done with an in-line style tag to take advantage of more easily selecting the relevant dom elements, while also not affecting the CSS on any other page.

Closes #44

2023-11-06 13:34 UTC, mtthgn commented on content/text.md
> +I have another text system here that is much more powerful (as in, really working on every video mode and has a printf too) than what's described in this page. However, it's rather large, not complet
This is the line I mentioned in Discord where `coranac.com` is still referenced to download tonclib. At a glance, there was one or two other markdown files referencing this as well.

2023-11-06 13:38 UTC, mtthgn commented on content/text.md
> +</style>
These styles were largely taken from coranac's stylesheet, and then modified to use the relevant mdbook variables.  If we'd like, we could move this to a css file and include it as an additional css file, as outlined by mdbook's ["Configuring Renderers"](https://rust-lang.github.io/mdBook/format/configuration/renderers.html) documentation.

I didn't go this route because I was unsure whether we want this additional CSS burden on every pageload for the docs.

2023-11-06 17:51 UTC, avivace requested changes
Seems great to me! I just converted the warning/info boxes to block quotes until we have a more consistent way to style those.

Also there is a table not visible in dark themes

2023-11-06 17:51 UTC, avivace commented on content/text.md
> +<table id="tbl:bupshade"
this table doesn't render correctly with dark theme

2023-11-06 17:51 UTC, avivace commented on content/text.md
> +</style>
I think this is fine, we can move to an external CSS afterwards!

2023-11-07 02:44 UTC, mtthgn commented on content/text.md
> +<table id="tbl:bupshade"
Alright, the styles are updated! On coranac, it had styling similar to the other one I customized. Making it use that made the demonstration much clearer, and then just made sure it was horizontally centered.

### Light
<img width="757" alt="Screenshot 2023-11-06 at 8 40 09 PM" src="https://github.com/gbadev-org/tonc/assets/543059/7cad6044-4416-4fae-b47d-e6b8df7efa83">

### Rust
<img width="769" alt="Screenshot 2023-11-06 at 8 39 58 PM" src="https://github.com/gbadev-org/tonc/assets/543059/ea159e92-0ff5-4746-8e63-b7514f5a1ac6">

### Coal
<img width="761" alt="Screenshot 2023-11-06 at 8 39 47 PM" src="https://github.com/gbadev-org/tonc/assets/543059/2af39a23-24ba-4be3-b6d0-bb70012e9627">

### Navy
<img width="765" alt="Screenshot 2023-11-06 at 8 39 38 PM" src="https://github.com/gbadev-org/tonc/assets/543059/9bd0905c-0e46-4964-8bf0-ce6b3ef15de5">

### Ayu
<img width="779" alt="Screenshot 2023-11-06 at 8 37 57 PM" src="https://github.com/gbadev-org/tonc/assets/543059/9db2f89b-45a3-4421-b7bf-212dbd438a5f">

2023-11-07 19:16 UTC, avivace approved these changes
Amazing!! Thanks

2023-11-07 19:16 UTC, merged