Convert "Vectors and Matrices" to Markdown
gbadev-org/tonc pull request #90
Opened 2023-12-22 05:32 UTC by mtthgn

The final page! Lots of equations in this one 😅 

Closes #48

2023-12-22 14:42 UTC, avivace requested changes

2023-12-22 14:42 UTC, avivace commented on content/matrix.md
> +{\*@eq-eqset}b is called the <dfn>coefficient matrix</dfn>, in which only the coefficients of the variables are written down. The <dfn>augmented matrix</dfn> ({@eq:eqset}c) also contains the right-ha
I don't think this is resolving correctly, as I'm seeing `{*@eq-eqset}b`

2023-12-22 15:39 UTC, mtthgn commented on content/matrix.md
> +{\*@eq-eqset}b is called the <dfn>coefficient matrix</dfn>, in which only the coefficients of the variables are written down. The <dfn>augmented matrix</dfn> ({@eq:eqset}c) also contains the right-ha
oh whoops, I'll fix.

2023-12-22 16:42 UTC, mtthgn commented
@avivace that issue is resolved! Good catch!

2023-12-25 22:51 UTC, avivace approved these changes

2023-12-25 22:51 UTC, merged